### ISSUE TITLE
no main manifest attribute, in subtitle-1.1.1.jar

### ISSUE THREAD

**Issue by sasha-bichkov** [nomalab/subtitle#33]
Hello!

I created an executable jar using maven in the root directory of the repository.
Once it was created, I ran the tool to convert my SRT to STL, but I got the following error: "no main manifest attribute, in subtitle-1.1.1.jar" and didn't get any output.

I tried to convert [this SRT](https://checksub-video-asset.s3.eu-west-1.amazonaws.com/CREFOAS2E082_LaSTARduKEBABvalidetilceRESTOLIBANAIS_sub_FR_CheckSub.srt).

**Comment by Romanelaf** [comment]
Hello !

You have to run subtitle-*-jar-with-dependencies.jar package, because we use assembly build with all the dependencies in the jar file. 
I will update Readme to clarify this part and will remove the default .jar in configuration to avoid confusion. 
Let me know if you need an executable without included dependencies, so I will update the configuration.

I also set a default vertical position in our STL writer, in order to convert SRT files to STL. (https://github.com/nomalab/subtitle/commit/f4122aa4cb2d8f0796b3467b22c3500e2faee1d1)

**Comment by sasha-bichkov** [comment]
@Romanelaf thank you!
"_subtitle-*-jar-with-dependencies.jar_" works as expected!
